name = "rs4lapce"
version = "0.2.0"
display-name = "Rs4Lapce"
author = "HTGAzureX1212"
description = "Rust plugin for Lapce, powered by Rust Analyzer"
repository = "https://github.com/TeamHarTex/rs4lapce"
wasm = "bin/rs4lapce.wasm"
icon = "rust-logo.svg"

[activation]
language = ["rust"]
workspace-contains = ["*/Cargo.toml"]

[config."rustAnalyzerBuilds.nightly"]
default = false
description = "Whether to fetch daily nightly builds of rust-analyzer for usage in the editor."

[config."rustAnalyzer.cargo.buildScripts.enable"]
default = false
description = "Whether to run build scripts for more precise code analysis."
